In [1]:
import numpy as np

In [3]:
arr = np.arange(5)
arr

In [4]:
np.save('myarray', arr)

In [5]:
arr = np.arange(10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr1 = np.load('myarray.npy')
arr1

array([0, 1, 2, 3, 4])

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.savez('zippedarray.npz',x=arr1,y=arr)

In [13]:
arv_arr = np.load('zippedarray.npz')

In [14]:
arv_arr['x']

array([0, 1, 2, 3, 4])

In [15]:
arv_arr['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.savetxt('savedtxt.txt', x, delimiter=)