In [3]:
import numpy as np

In [5]:
my_list1 = [1,2,3,4]
my_array1 = np.array(my_list1)
my_array1

array([1, 2, 3, 4])

In [7]:
myl2 = [11,222,33,44]
ml = [my_list1, myl2]
ma2 = np.array(ml)
ma2

array([[  1,   2,   3,   4],
       [ 11, 222,  33,  44]])

In [8]:
ma2.shape


(2, 4)

In [9]:
ma2.dtype

dtype('int64')

In [15]:
a = np.zeros(6)
a

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [16]:
c = np.empty(4)
c

array([ 0.,  0.,  0.,  0.])

In [17]:
np.eye(6)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [18]:
a.dtype


dtype('float64')

In [19]:
b = np.ones([5,7])
b

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [ ]:
np.arrange(5)