In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3,4,5,5])
x

array([1, 2, 3, 4, 5, 5])

In [5]:
x[0]
x[:4]

array([1, 2, 3, 4])

In [6]:
np.save('xx', x)

In [8]:
np.load('xx.npy')

array([1, 2, 3, 4, 5, 5])