In [43]:
#This is a standard classification problem.
#out of lot of classifiers I have used Logistic Regression, Decision Tree and experimented with MLP Neural Network classifier.

#Assumptions: Red and White are replaced in the dataset preprocessing as 1 and 2 respectively.
#Acuracy Scores : ~52% using Logistic Regression, ~60% using Decision Tree and <50% using Neural Network.(Which needs improvement by fine tuning the model)

#NOTE: These models can be improved and fine tuned given time and expertise.

In [55]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.cross_validation import train_test_split
from sklearn.neural_network import MLPClassifier

In [20]:
data = pd.read_csv('wine_dataset.csv', header=0)
data = data.dropna()
print(data.shape)
print(list(data.columns))

(6497, 13)
['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar', 'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality', 'style']


In [21]:
mapping = {'red': 1, 'white': 2}
data = data.replace({'style': mapping})

In [22]:
X = data.drop('quality', axis=1)
y = data.quality
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
print(X_train)

      fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
3731            7.1             0.220         0.32           16.90      0.056   
1651            6.2             0.160         0.33            1.10      0.057   
5060            6.7             0.240         0.30            3.85      0.042   
1303            8.0             0.280         0.44            1.80      0.081   
474            10.5             0.280         0.51            1.70      0.080   
4304            6.7             0.260         0.39            6.40      0.171   
2731            6.8             0.390         0.31           14.35      0.043   
1855            6.3             0.350         0.30            5.70      0.035   
2752            5.3             0.395         0.07            1.30      0.035   
5137            6.5             0.280         0.25            4.80      0.029   
567             8.7             0.700         0.24            2.50      0.226   
1949            6.3         

In [23]:
print(y_train)

3731    6
1651    7
5060    8
1303    5
474     6
4304    6
2731    5
1855    7
2752    6
5137    7
567     6
1949    7
2267    6
4053    5
2089    6
5776    6
6320    6
3900    5
1979    7
4205    6
666     6
3655    5
5656    6
3943    6
2126    6
6256    7
4663    5
5064    6
5329    6
2527    5
       ..
99      6
2496    6
1871    5
2046    6
4851    8
5072    8
2163    5
6036    6
6216    7
2893    4
537     6
1701    5
2897    6
2222    5
2135    5
2599    7
705     5
6458    6
3468    7
5924    5
5874    6
4373    8
1033    6
5827    6
4859    6
4931    7
3264    8
1653    6
2607    7
2732    5
Name: quality, Length: 4872, dtype: int64


In [24]:
X_train.shape

(4872, 12)

In [25]:
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [26]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[  0   0   6   4   0   0   0]
 [  0   0  39  16   0   0   0]
 [  0   0 296 235   1   0   0]
 [  0   0 175 521   8   0   0]
 [  0   0  20 242  12   0   0]
 [  0   0   2  44   1   0   0]
 [  0   0   0   3   0   0   0]]


In [27]:
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(classifier.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.51


In [28]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          3       0.00      0.00      0.00        10
          4       0.00      0.00      0.00        55
          5       0.55      0.56      0.55       532
          6       0.49      0.74      0.59       704
          7       0.55      0.04      0.08       274
          8       0.00      0.00      0.00        47
          9       0.00      0.00      0.00         3

avg / total       0.48      0.51      0.45      1625



/Users/bkdas/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [35]:
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [36]:
prediction = clf.score(X_test, y_test)
print("\nThe confidence score:\n")
print(prediction)


The confidence score:

0.5963076923076923


In [37]:
y_pred = clf.predict(X_test)

In [42]:
#converting the numpy array to list
j=np.array(y_pred).tolist()

#printing first 5 predictions
print("\nThe prediction:\n")
for i in range(0,5):
    print(j[i])
    
#printing first five expectations
print("\nThe expectation:\n")
print(y_test.head())


The prediction:

6
6
6
4
8

The expectation:

5316    6
5210    6
3518    6
1622    5
2443    8
Name: quality, dtype: int64


In [44]:
clf_mlp = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)

In [46]:
clf_mlp.fit(X_train, y_train)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [50]:
nn_predictions = clf_mlp.predict(X_test)

In [52]:
print(nn_predictions)

[6 6 5 ... 6 6 6]


In [54]:
print(classification_report(y_test,nn_predictions))

             precision    recall  f1-score   support

          3       0.00      0.00      0.00        10
          4       0.00      0.00      0.00        55
          5       0.48      0.32      0.38       532
          6       0.45      0.72      0.55       704
          7       0.40      0.20      0.27       274
          8       0.00      0.00      0.00        47
          9       0.00      0.00      0.00         3

avg / total       0.42      0.45      0.41      1625



/Users/bkdas/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
