In [2]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [7]:
A = np.random.rand(10)
A

array([ 0.51651636,  0.4266061 ,  0.32706409,  0.38966222,  0.00384077,
        0.98934501,  0.80054288,  0.97746568,  0.96996434,  0.50790248])

In [8]:
B = np.random.randn(10)
B

array([ 1.29532998,  1.15104509,  0.39169779,  0.38897134,  0.03283871,
        0.15833826,  1.39411219,  0.78231343, -1.13193781, -0.15227323])

In [9]:
np.add(A,B)

array([ 1.81184634,  1.57765119,  0.71876188,  0.77863356,  0.03667948,
        1.14768327,  2.19465507,  1.75977911, -0.16197347,  0.35562924])

In [10]:
np.maximum(A,B)

array([ 1.29532998,  1.15104509,  0.39169779,  0.38966222,  0.03283871,
        0.98934501,  1.39411219,  0.97746568,  0.96996434,  0.50790248])

In [11]:
np.minimum(A,B)

array([ 0.51651636,  0.4266061 ,  0.32706409,  0.38897134,  0.00384077,
        0.15833826,  0.80054288,  0.78231343, -1.13193781, -0.15227323])

In [13]:
website = "www.xyz.com"
import webbrowser
webbrowser.open(website)

True